#!/bin/bash

source $HOME/.dotfiles/bash/bash-git-prompt/prompt-colors.sh

info () {
  printf "\r  [ ${BoldBlue}..${ResetColor} ] $1\n"
}

user () {
  printf "\r  [ ${BoldCyan}??${ResetColor} ] $1\n"
}

success () {
  printf "\r  [ ${BoldGreen}OK${ResetColor} ] $1\n"
}

warning () {
  printf "\r  [ ${BoldYellow}!!${ResetColor} ] $1\n"
}

fail () {
  printf "\r  [${BoldRed}FAIL${ResetColor}] $1\n"
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "Skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

is_symlink () {
  local file=$1
  if [ -L "$file" ]
  then
    return 0
  else
    return 1
  fi
}
