#!/bin/bash
#
# This script will install the full configuration of the tiborsimon/dotfiles repo.
# It will use a symlinked solution: it will symlink the configuration files located in
# the .dotfiles folder's subfolders. With this approach, you will be able to separate
# the configurations from each others.
#
# This script can be used if you already have cloned the dotfiles repo, but you want to update
# to the latest version.
#
# To be able to use this file, you have to fill out the global variables below.
#
# Usage: run the script from the ~/.dotfiles folder.

LINUX_PACKAGE_MANAGER=yum

#set -e
source functions/commons

#----------------------------------------------------------------------------------------
#  F U N C T I O N S
#----------------------------------------------------------------------------------------

install_dotfiles () {
  info 'Installing dotfiles..'
  local overwrite_all=false backup_all=false skip_all=false
  for src in $(find -H "$HOME/.dotfiles" -maxdepth 2 -name '*.symlink' -not -path '*.git*'); do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_python () {
  info 'Installing pip and python dev tools..'
  sudo apt-get install python-pip python-dev python-setuptools
  success 'pip and python dev tools installed!'
  info 'Installing pip3..'
  sudo apt-get install python3-pip
  success 'pip3 installed!'
  info 'Upgrading pip and pip3..'
  sudo -H pip2 install --upgrade pip
  sudo -H pip3 install --upgrade pip
  success 'pip and pip3 upgraded!'
  info 'Installing necessary packages..'
  sudo -H pip2 install setuptools virtualenv projects
  sudo -H pip3 install setuptools virtualenv jupyter
  success 'Packages installed!'
}

install_mc () {
  info 'Installing mc config..'
  if [ ! -d "$HOME/.config" ]; then
    mkdir $HOME/.config
  fi
  local overwrite_all=false backup_all=false skip_all=false
  link_file "$HOME/.dotfiles/mc" "$HOME/.config/mc"
  success 'Mc config installed!'
}

install_kicad () {
  info 'Installing KiCad..'
  sudo add-apt-repository --yes ppa:js-reynaud/kicad-4
  sudo apt update
  sudo apt install kicad
  success 'KiCad installed!'
}

install_vimplug () {
  info 'Installing VimPlug..'
  curl -sSfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  success 'VimPlug installed!'
}

install_pip_tools () {
  info 'Installing pip tools..'
  pip install projects
  pip install bpython
  success 'Pip tools installed!'
}

install_node_js () {
  info 'Installing Node.js..'
	which node > /dev/null
  if [[ $? != 0 ]]; then
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    sudo apt-get install -y nodejs
    success 'Node.js installed!'
    info 'Installing global Node.js packages..'
    sudo npm install --silent -g local-web-server
    info 'Global Node.js packages installed!'
  else
    warning 'Node.js was already installed.. Nothing to do.'
  fi
}

clone_essential_projects () {
  info 'Cloning essential repositories..'
  if [ ! -d ~/projects ]; then
    mkdir ~/projects
  fi
  if [ ! -d ~/projects/notebook ]; then
    git clone --depth 1 git@github.com:tiborsimon/notebook.git ~/projects/notebook
  fi
  if [ ! -d ~/projects/worklog ]; then
    git clone --depth 1 git@github.com:tiborsimon/worklog.git ~/projects/worklog
  fi
  if [ ! -d ~/projects/site ]; then
    git clone --depth 1 git@github.com:tiborsimon/tiborsimon.io-core.git ~/projects/site
  fi
  success 'Essential repositories cloned.'
}

excute_linux_packages_file () {
  while true; do
    user "Do you want to install software packages?  [${BoldGreen}y${ResetColor}]es, [${BoldGreen}s${ResetColor}]kip"
    read -n 1 action
    case "$action" in
      y ) user 'What is the package manager for this platform?'
        read -e LINUX_PACKAGE_MANAGER
        for app in $(cat $HOME/.dotfiles/linux/packages.txt); do
          info "Installing $app.."
          if sudo $LINUX_PACKAGE_MANAGER install -y $app>pof 2>&1; then
            success "$app installed."
          else
            warning "$app installation failed! Error: \n$(cat pof)"
          fi
          rm -f pof
        done
        success 'Done'
        break
        ;;
      s ) success 'Skipped..'
        break
        ;;
      * ) warning "Wrong answer! Type ${BoldGreen}y${ResetColor} or ${BoldGreen}s${ResetColor}."
        ;;
    esac
  done
}

deploy_synaptic_config_file () {
  while true; do
    user "Do you want to deploy the Synaptic Touchpad configuration file? [${BoldGreen}y${ResetColor}]es, [${BoldGreen}s${ResetColor}]kip"
    read -n 1 action
    case "$action" in
      y ) info "Deploying synaptic configuration file."
        test -d /etc/X11/xorg.conf.d || sudo mkdir /etc/X11/xorg.conf.d
        sudo ln -s ~/.dotfiles/xorg/50-synaptic.conf /etc/X11/xorg.conf.d/50-synaptic.conf
        success "Synaptic configuration file deployed."
        break
        ;;
      s ) success 'Skipped..'
        break
        ;;
      * ) warning "Wrong answer! Type ${BoldGreen}y${ResetColor} or ${BoldGreen}s${ResetColor}."
        ;;
    esac
  done
}


#----------------------------------------------------------------------------------------
#  F U N C T I O N S   C A L L S
#----------------------------------------------------------------------------------------

info "Installing Linux related config"
install_dotfiles
excute_linux_packages_file
install_python
install_node_js
install_mc
install_vimplug
install_kicad

success 'Dotfiles has been deployed.'
