#!/bin/sh
#
# This script will install the vim configuration part of the tiborsimon/dotfiles repo. 
# It won't use the symlinked solution as it will create the the .vimrc file and
# the .vim folder instead. It also installs the Vim-Plug plugin manager, and installs the 
# plugins listed in the .vimrc file. 
#
# After the script finished, you will have a full vim configuration on your machine.
#
# This solution is useful if you have spun up a new virtual machine, and you only want to edit 
# files with comfort, and do not want to deploy the whole dotfile system. You won't be able to push
# back changes you make in the config.
#
# Usage: issue the following command on your machine: sh <(curl -fsSL tiborsimon.io/vimrc)

#----------------------------------------------------------------------------------------
#  C O M M O N   F U N C T I O N S
#----------------------------------------------------------------------------------------

RESET=$(tput sgr0)

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)

BOLD=$(tput bold)

info () {
  printf "\r  [ ${BOLD}${LBLUE}..${RESET} ] $1\n"
}

user () {
  printf "\r  [ ${BOLD}${CYAN}??${RESET} ] $1\n"
}

success () {
  printf "\r  [ ${BOLD}${GREEN}OK${RESET} ] $1\n"
}

warning () {
  printf "\r  [ ${BOLD}${YELLOW}!!${RESET} ] $1\n"
}

fail () {
  printf "\r  [${BOLD}${RED}FAIL${RESET}] $1\n"
}


#----------------------------------------------------------------------------------------
#  I N S T A L L   S C R I P T
#----------------------------------------------------------------------------------------

echo ''
echo '---------------------------------------------------------------------------------'
echo "      T I B O R   S I M O N ' S   V I M   C O N F I G U R A T I O N"
echo '---------------------------------------------------------------------------------'
echo ''

user_answered=0
until [ user_answered -eq 1]; do
  if [ -f ~/.vimrc ] || [ -d ~/.vim ]; then
    user "Old vim configuration already exist. This script will override it! [${BOLD}${GREEN}D${RESET}]o it, [${BOLD}${GREEN}a${RESET}]bort"
    read -n 1 action
  
    case "$action" in
    D ) rm -rf $HOME/.vim
        rm -f $HOME/.vimrc
        success "Old vim config deleted."
        user_answered=1
        ;;
    a ) success 'Bootstrap script aborted.'
        echo ''
        exit
        ;;
    * ) warning 'Wrong answer!'
        ;;
    esac
  fi
done

# Loading .vimrc file
info 'Downloading .vimrc file..'
curl -fsSL https://raw.githubusercontent.com/tiborsimon/dotfiles/master/vim/vimrc.symlink> ~/.vimrc
success '.vimrc file downloaded.'

# Loading Vim-Plug package manager to the .vim folder
info 'Installing vim-lug..'
curl -sSfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
success 'Vim-plug installed.'
success 'Finished!'
