# typing repetion speed icrease
xset r rate 250 83 > /dev/null

# map caps lock to ctrl
setxkbmap -option ctrl:nocaps

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

export PATH="$HOME/.cargo/bin:$PATH"
export W3MIMGDISPLAY_PATH=~/.dotfiles/bin/my-w3m-delay
