.PHONY: install-bash
install-bash:
	@./utils/install-configs.bash bash

.PHONY: install-docker
install-docker:
	@./utils/install-configs.bash docker

.PHONY: install-emacs
install-emacs:
	@./utils/install-configs.bash emacs

.PHONY: install-git
install-git:
	@./utils/install-configs.bash git

.PHONY: install-kde
install-kde:
	@./utils/install-configs.bash kde

.PHONY: install-ledger
install-ledger:
	@./utils/install-configs.bash ledger

.PHONY: install-openvpn
install-openvpn:
	@./utils/install-configs.bash openvpn

.PHONY: install-profile
install-profile:
	@./utils/install-configs.bash profile

.PHONY: install-ranger
install-ranger:
	@./utils/install-configs.bash ranger

.PHONY: install-ripgrep
install-ripgrep:
	@./utils/install-configs.bash ripgrep

.PHONY: install-udevmon
install-udevmon:
	@./utils/install-configs.bash udevmon

.PHONY: install-zsh
install-zsh:
	@./utils/install-configs.bash zsh

