.PHONY: install-bash
install-bash:
	@./utils/install-configs.bash bash

.PHONY: install-bpytop
install-bpytop:
	@./utils/install-configs.bash bpytop

.PHONY: install-docker
install-docker:
	@./utils/install-configs.bash docker

.PHONY: install-doom-emacs
install-doom-emacs:
	@./utils/install-configs.bash doom-emacs

.PHONY: install-emacs
install-emacs:
	@./utils/install-configs.bash emacs

.PHONY: install-firefox
install-firefox:
	@./utils/install-configs.bash firefox

.PHONY: install-firejail
install-firejail:
	@./utils/install-configs.bash firejail

.PHONY: install-firewall
install-firewall:
	@./utils/install-configs.bash firewall

.PHONY: install-fonts
install-fonts:
	@./utils/install-configs.bash fonts

.PHONY: install-git
install-git:
	@./utils/install-configs.bash git

.PHONY: install-keybase
install-keybase:
	@./utils/install-configs.bash keybase

.PHONY: install-kitty
install-kitty:
	@./utils/install-configs.bash kitty

.PHONY: install-ledger
install-ledger:
	@./utils/install-configs.bash ledger

.PHONY: install-logind
install-logind:
	@./utils/install-configs.bash logind

.PHONY: install-lunar-vim
install-lunar-vim:
	@./utils/install-configs.bash lunar-vim

.PHONY: install-machine
install-machine:
	@./utils/install-configs.bash machine

.PHONY: install-neovim
install-neovim:
	@./utils/install-configs.bash neovim

.PHONY: install-nodejs
install-nodejs:
	@./utils/install-configs.bash nodejs

.PHONY: install-openvpn
install-openvpn:
	@./utils/install-configs.bash openvpn

.PHONY: install-power
install-power:
	@./utils/install-configs.bash power

.PHONY: install-python
install-python:
	@./utils/install-configs.bash python

.PHONY: install-ranger
install-ranger:
	@./utils/install-configs.bash ranger

.PHONY: install-ripgrep
install-ripgrep:
	@./utils/install-configs.bash ripgrep

.PHONY: install-shell
install-shell:
	@./utils/install-configs.bash shell

.PHONY: install-sudoers
install-sudoers:
	@./utils/install-configs.bash sudoers

.PHONY: install-sway
install-sway:
	@./utils/install-configs.bash sway

.PHONY: install-task
install-task:
	@./utils/install-configs.bash task

.PHONY: install-tools
install-tools:
	@./utils/install-configs.bash tools

.PHONY: install-udevmon
install-udevmon:
	@./utils/install-configs.bash udevmon

.PHONY: install-vault
install-vault:
	@./utils/install-configs.bash vault

.PHONY: install-vim
install-vim:
	@./utils/install-configs.bash vim

.PHONY: install-vscode
install-vscode:
	@./utils/install-configs.bash vscode

.PHONY: install-wofi
install-wofi:
	@./utils/install-configs.bash wofi

.PHONY: install-zathura
install-zathura:
	@./utils/install-configs.bash zathura

.PHONY: install-zsh
install-zsh:
	@./utils/install-configs.bash zsh

