.PHONY: install-alacritty
install-alacritty:
	@./configs/install.bash alacritty

.PHONY: install-bash
install-bash:
	@./configs/install.bash bash

.PHONY: install-bspwm
install-bspwm:
	@./configs/install.bash bspwm

.PHONY: install-compton
install-compton:
	@./configs/install.bash compton

.PHONY: install-emacs
install-emacs:
	@./configs/install.bash emacs

.PHONY: install-fish
install-fish:
	@./configs/install.bash fish

.PHONY: install-fonts
install-fonts:
	@./configs/install.bash fonts

.PHONY: install-git
install-git:
	@./configs/install.bash git

.PHONY: install-keyboard
install-keyboard:
	@./configs/install.bash keyboard

.PHONY: install-ledger
install-ledger:
	@./configs/install.bash ledger

.PHONY: install-lemonbar
install-lemonbar:
	@./configs/install.bash lemonbar

.PHONY: install-moc
install-moc:
	@./configs/install.bash moc

.PHONY: install-profile
install-profile:
	@./configs/install.bash profile

.PHONY: install-pypi
install-pypi:
	@./configs/install.bash pypi

.PHONY: install-python
install-python:
	@./configs/install.bash python

.PHONY: install-ranger
install-ranger:
	@./configs/install.bash ranger

.PHONY: install-redshift
install-redshift:
	@./configs/install.bash redshift

.PHONY: install-rust
install-rust:
	@./configs/install.bash rust

.PHONY: install-tmux
install-tmux:
	@./configs/install.bash tmux

.PHONY: install-vim
install-vim:
	@./configs/install.bash vim

