#! /bin/sh

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9

bspc config top_padding           0
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc config border_width          2
bspc config window_gap            9

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config swallow_first_click   true

bspc config normal_border_color   "#555555"
bspc config focused_border_color  "#f1c40f"

# Setting up applications
bspc rule --add Emacs state=tiled
bspc rule --add Firefox state=tiled focus=on desktop='^2' follow=on
bspc rule --add Gimp desktop='^8' state=tiled follow=on layout=monocle
bspc rule --add Screenkey manage=off
bspc rule --add Skype state=tiled focus=on desktop='^9' follow=on

# bspc config desktop 2 --layout monocle
# bspc config desktop 9 --layout monocle

my-lemonbar-init
