#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config top_padding           0
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc config border_width          2
bspc config window_gap            9

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config swallow_first_click   true

bspc config normal_border_color   "#555555"
bspc config focused_border_color  "#f1c40f"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled focus=on desktop='^4' follow=on
